name: artaircleaner
description: ArtAirCleaner Flutter app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
