<!DOCTYPE html>
<html>
  <head>
    <base href="/artaircleaner/">
    <meta charset="UTF-8" />
    <meta name="description" content="ArtAirCleaner" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ArtAirCleaner</title>
    <link rel="manifest" href="manifest.json">
  </head>
  <body>
    <!-- Flutter bootstrap (no service worker) -->
    <script src="flutter_bootstrap.js" async></script>
  </body>
</html>
