<!DOCTYPE html>
<html>
  <head>
    <base href="/artaircleaner/">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <title>ArtAirCleaner</title>
    <link rel="manifest" href="manifest.json">
    <meta name="theme-color" content="#000000">
    <link rel="icon" type="image/png" href="favicon.png"/>

    <!-- Optional: kill old service workers to avoid white-screen due to stale cache -->
    <script>
      if ('serviceWorker' in navigator) {
        navigator.serviceWorker.getRegistrations().then(rs => rs.forEach(r => r.unregister()));
      }
    </script>
  </head>
  <body>
    <!-- Flutter loader -->
    <script src="flutter_bootstrap.js" async></script>
  </body>
</html>
